// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Reflection;

namespace Cake.Generator;

public partial class CakeGenerator
{
    private static readonly Assembly CakeGeneratorCoreAssembly = typeof(CakeGenerator).Assembly;
    public static readonly string CakeGeneratorDate = DateTimeOffset.UtcNow.ToString("yyyy-MM-dd HH:mm:ssZ");
    public static readonly string CakeGeneratorVersion = CakeGeneratorCoreAssembly.GetCustomAttribute<AssemblyVersionAttribute>()?.Version
                         ?? CakeGeneratorCoreAssembly.GetName().Version?.ToString()
                         ?? "Unknown";
    public static readonly string CakeGeneratorInformationalVersion = CakeGeneratorCoreAssembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion ?? "Unknown";
    public static readonly string CakeGeneratorNuGetVersion = CakeGeneratorInformationalVersion.Split(['+'], 2, StringSplitOptions.RemoveEmptyEntries).FirstOrDefault() ?? "Unknown";

    /// <summary>
    /// Generates constants including the version of Cake.Generator.Core.
    /// </summary>
    /// <param name="compilation">The compilation context.</param>
    /// <returns>The generated constants source code.</returns>
    private static string GenerateConstants()
        =>
            $$"""
            // <auto-generated />
            #nullable enable

            /// <summary>
            /// Contains constants generated by Cake.Generator.Core.
            /// </summary>
            public static partial class Program
            {
                /// <summary>
                /// The version of Cake.Generator.Core used to generate these aliases.
                /// </summary>
                public const string CakeGeneratorDate = "{{CakeGeneratorDate}}";
                public const string CakeGeneratorVersion = "{{CakeGeneratorVersion}}";
                public const string CakeGeneratorInformationalVersion = "{{CakeGeneratorInformationalVersion}}";
                public const string CakeGeneratorNuGetVersion = "{{CakeGeneratorNuGetVersion}}";
            }
            """;
}