// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

namespace Cake.Generator;

public partial class CakeGenerator
{
    private static string GenerateModules(IList<ModuleInfo> modules)
    {
        var sb = new StringBuilder();
        sb.AppendLine(
            """
            // <auto-generated/>
            #nullable enable

            using Cake.Cli;
            using Microsoft.Extensions.DependencyInjection;

            public static partial class Program
            {
                private static partial class Helper
                {
                    /// <summary>
                    /// Registers all discovered Cake modules with the service collection.
                    /// This method is called from GetServiceProvider after AddCakeCore.
                    /// </summary>
                    /// <param name="services">The service collection to register modules with.</param>
                    static partial void RegisterModules(IServiceCollection services)
                    {
            """);

        foreach (var module in modules)
        {
            sb.AppendLine(
                $$"""
                            // Register {{module.Name}}
                            services.UseModule<{{module.FullName}}>();

                """);
        }

        sb.AppendLine(
            """
                    }
                }
            }
            """);

        return sb.ToString();
    }
}
