// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Runtime.CompilerServices;

/// <summary>
/// Module initializer for configuring Verify settings.
/// </summary>
internal static class ModuleInit
{
    /// <summary>
    /// Initialize Verify configuration for source generator testing.
    /// </summary>
    [ModuleInitializer]
    public static void Initialize()
    {
        // Initialize source generator support
        VerifySourceGenerators.Initialize();

        // Initialize DiffPlex for better diffs
        VerifyDiffPlex.Initialize();

        // Set default scrubbers for generated code
        VerifierSettings.ScrubLinesContaining("GeneratedCodeAttribute");
        VerifierSettings.ScrubLinesContaining("CompilerGeneratedAttribute");
        VerifierSettings.ScrubLinesContaining("// <auto-generated");
        VerifierSettings.ScrubLinesContaining("#nullable");
        VerifierSettings.ScrubLinesWithReplace(
            line => line.StartsWith("    public const string CakeGenerator")
                        ? line
                            .Replace(
                                $"CakeGeneratorDate = \"{CakeGenerator.CakeGeneratorDate}\"",
                                "CakeGeneratorDate = \"2025-06-07 17:28:44Z\"")
                            .Replace(
                                $"CakeGeneratorVersion = \"{CakeGenerator.CakeGeneratorVersion}\"",
                                "CakeGeneratorVersion = \"5.0.25158.20967\"")
                            .Replace(
                                $"CakeGeneratorInformationalVersion = \"{CakeGenerator.CakeGeneratorInformationalVersion}\"",
                                "CakeGeneratorInformationalVersion = \"5.0.25158.20967-local+e5616adddc7809416d304d094c97aced16dcd1a9\"")
                            .Replace(
                                $"CakeGeneratorNuGetVersion = \"{CakeGenerator.CakeGeneratorNuGetVersion}\"",
                                "CakeGeneratorNuGetVersion = \"5.0.25158.20967-local\"")
                        : line);

        // Add custom scrubbers for timestamp-like content
        VerifierSettings.AddScrubber(builder => builder.Replace(@"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}", "TIMESTAMP"));
    }
}
