name: Build
on:
  push:
    branches:
      - develop
      - main
  pull_request:
jobs:
  build:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET SDK 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Install .NET SDK 9.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      - name: Install .NET Core SDK (global.json)
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Build Cake Generator & SDK
        uses: cake-build/cake-action@master
        env:
          AZURE_DEVOPS_NUGET_API_KEY: ${{ secrets.AZURE_DEVOPS_NUGET_API_KEY }}
          AZURE_DEVOPS_NUGET_API_URL: ${{ secrets.AZURE_DEVOPS_NUGET_API_URL }}
        with:
          project-path: src/Cake.Generator.TestApp/Cake.Generator.TestApp.csproj
          target: GitHubActions